openapi: 3.0.0
info:
  title: foodsnap
  description: "料理メニューを中心にアプローチし、料理の魅力を直感的に伝えるアプリ"
  version: 1.0.0
tags:
  - name: "users"
    description: "ユーザーに関わるAPI"

servers:
  - url: http://localhost:8787/api
    description: "ローカル用"

paths:
  /users/register:
    post:
      summary: "user登録(eamil & password)"
      description: "メールアドレスでのユーザー登録"
      tags:
        - users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - email
                - password
              properties:
                name:
                  type: string
                  description: "ユーザ名"
                  example: "田中 太郎"
                  minLength: 1
                  maxLength: 12
                email:
                  type: string
                  description: "メールアドレス"
                  example: "example@example.com"
                  format: email
                  minLength: 1
                password:
                  type: string
                  description: "パスワード"
                  example: "Password"
                  minLength: 8
                  maxLength: 20
                  format: password
      responses:
        201:
          description: "user登録成功時"
          content:
            application/json:
              schema:
                type: object
                properties:
                  email:
                    type: string
                    description: "登録されたメールアドレス"
                    example: "example@example.com"
                    format: email
        400:
          description: "バリデーションエラー"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "エラーメッセージ"
                    example: "バリデーションエラーが発生しました"
                  errors:
                    type: object
                    description: "各フィールドのエラー詳細"
                    properties:
                      name:
                        type: string
                        description: "ユーザー名のバリデーションエラー"
                        example: "ユーザー名は必須です。"
                        # enumは候補を表す。
                        enum:
                          - "ユーザー名は必須です。"
                          - "ユーザー名は12文字以下で入力してください。"
                      email:
                        type: string
                        description: "メールアドレスのバリデーションエラー"
                        example: "メールアドレスは必須です。"
                        enum:
                          - "メールアドレスは必須です。"
                          - "正しいメールアドレス形式で入力してください。"
                          - "このメールアドレスは既に登録されています。" # メアド重複も400 bad requestに含める。
                      password:
                        type: string
                        description: "パスワードのバリデーションエラー"
                        example: "パスワードは必須です。"
                        enum:
                          - "パスワードは必須です。"
                          - "パスワードは8文字以上20文字以下で入力してください。"
        500:
          $ref: "#/components/responses/serverError"

  /auth/google:
    get:
      summary: "user登録&ログイン(Google認証)"
      description: "GoogleプロバイダーでのOAuth認証を開始し、Google認証画面にリダイレクトします"
      tags:
        - users
      responses:
        #ステータスコード302はリダイレクトを意味する。
        302:
          description: "Google認証画面へのリダイレクト"
          headers:
            Location:
              description: "Google OAuth認証URL"
              schema:
                type: string
                example: "https://accounts.google.com/oauth/authorize?client_id=..."
                format: url;
                description: "Google OAuth認証のURL"
        400:
          description: "リクエストエラー"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "エラーメッセージ"
                    example: "OAuth認証に失敗しました。"
        500:
          $ref: "#/components/responses/serverError"
  
  /auth/callback:
    post:
      summary: "ユーザー登録でcallbackされるAPI"
      description: "accessTokenを受け取って、ユーザー登録を確立させる"
      tags:
        - users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - accessToken
              properties:
                accessToken:
                  type: string
                  description: "URLから取得したtoken"
                  example: "cijij13213ubuihrqrhiu12moovwifof"
      responses:
        200:
          $ref: "#/components/responses/success"
        400:
          description: "トークンエラー"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "トークンエラー"
                    example: "accessTokenが無効、存在しません"
        500:
          $ref: "#/components/responses/serverError"
  /user/login:
    post:
      summary: "ユーザーログイン(email & password)"
      description: "email & passwordを受け取って、ユーザーをログイン状態にする"
      tags:
        - users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  description: "メールアドレス"
                  example: "example@example.com"
                  format: email
                  minLength: 1
                password:
                  type: string
                  description: "パスワード"
                  example: "Password"
                  minLength: 8
                  maxLength: 20
                  format: password
      responses:
        200:
          $ref: "#/components/responses/success"
        400:
          
      



# コンポーネント
components:
  responses:
    success:
      description: "成功時"
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                description: "success"
                example: "success"
    serverError:
      description: "サーバーエラー"
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                description: "サーバーエラーメッセージ"
                example: "サーバーエラーが発生しました"
    authError:
      description: "認証エラー"
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                description: "認証エラーメッセージ"
                example: "認証エラーが発生しました"
