openapi: 3.0.0
info:
  title: foodsnap
  description: "料理メニューを中心にアプローチし、料理の魅力を直感的に伝えるアプリ"
  version: 1.0.0
tags:
  - name: "users"
    description: "ユーザーに関わるAPI"

servers:
  - url: http://localhost:8787/api
    description: "ローカル用"

paths:
  /users/register:
    post:
      summary: "user登録"
      description: "supabaseを用いたuser登録。mail認証"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - email
                - password
              properties:
                name:
                  type: string
                  description: "ユーザ名"
                  example: "田中 太郎"
                  minLength: 1
                  maxLength: 12
                email:
                  type: string
                  description: "メールアドレス"
                  example: "example@example.com"
                  format: email
                  minLength: 1
                password:
                  type: string
                  description: "パスワード"
                  example: "Password"
                  minLength: 8
                  maxLength: 20
                  format: password
      responses:
        200:
          description: "user登録成功時"
          content:
            application/json:
              schema:
                type: object
                properties:
                  email:
                    type: string
                    description: "登録されたメールアドレス"
                    example: "example@example.com"
                    format: email
        400:
          description: "バリデーションエラー"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "エラーメッセージ"
                    example: "バリデーションエラーが発生しました"
                  errors:
                    type: object
                    description: "各フィールドのエラー詳細"
                    properties:
                      name:
                        type: string
                        description: "ユーザー名のバリデーションエラー"
                        example: "ユーザー名は必須です。"
                        # enumは候補を表す。
                        enum:
                          - "ユーザー名は必須です。"
                          - "ユーザー名は12文字以下で入力してください。"
                      email:
                        type: string
                        description: "メールアドレスのバリデーションエラー"
                        example: "メールアドレスは必須です。"
                        enum:
                          - "メールアドレスは必須です。"
                          - "正しいメールアドレス形式で入力してください。"
                          - "このメールアドレスは既に登録されています。" # メアド重複も400 bad requestに含める。
                      password:
                        type: string
                        description: "パスワードのバリデーションエラー"
                        example: "パスワードは必須です。"
                        enum:
                          - "パスワードは必須です。"
                          - "パスワードは8文字以上20文字以下で入力してください。"
        500:
          description: "サーバーエラー"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "サーバーエラーメッセージ"
                    example: "サーバーエラーが発生しました"

